import type { Metadata } from "next";
// import localFont from "next/font/local";
import "@/app/globals.css";
import { Sidebar } from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from '@clerk/nextjs'
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
        <body
          className={`bg-[#0f0f0f] antialiased`}
        >
          <div className="flex flex-col ">
            {/* Navbar at the top */}
            <Navbar />

            {/* Main content with Sidebar and Children */}
            <div className="flex flex-1">
              {/* Sidebar */}
              <Sidebar />

              {/* Main Content Area */}
              <div className="flex-1 overflow-auto p-4">
                {children}
              </div>
            </div>
          </div>
        </body>
      </html>
  );
}
